import type { Metadata } from "next";
import { poppins } from "@/fonts";
import "./globals.css";
import Navbar from "./components/landing/Navbar";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${poppins.variable} ${poppins.variable} bg-black text-[#f5f5f5] max-w-5xl mx-auto`}
			>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
